### PR TITLE
Issue #468, #467: header content positioning

### PR DESCRIPTION
**Pull request by jkva**
This PR:

* improves quicksearch styling and adds it to the page header
* adds responsive styling to the page header
* clarifies front-end workflow in the README

### CODE REVIEW

**Comment by abeverley** [comment]
Thanks, looks much better. Comments:

- Parameter search_text needs changing to search in the controller to make it work
- We need some way to make it obvious that a user is viewing filtered records when a search is live. This used to be done by replacing the view name header with "search results", but that has now gone with the new layout. Otherwise users forget that they are viewing a set of search results.
- I think there needs to be an easier way to clear the search

**Comment by jkva** [comment]
@abeverley 

> Parameter search_text needs changing to search in the controller to make it work

Sorted this view-side. 

> We need some way to make it obvious that a user is viewing filtered records when a search is live. > This used to be done by replacing the view name header with "search results", but that has now
> gone with the new layout. Otherwise users forget that they are viewing a set of search results.

Added it back in, amended with results counter

> I think there needs to be an easier way to clear the search

Besides the current "Clear" button?

**Comment by abeverley** [comment]
Thanks, that's good, but sorry, one more comment:

The height of the search box is slightly too small for the text on my screen (the "p" is chopped):
image

Maybe the font could be made smaller, and that would also allow more text on the screen (I feel the box is slightly too narrow at the moment for the text a user might be searching for).

**Comment by jkva** [comment]
@abeverley I've made the input larger:

image

**Comment by abeverley** [comment]
Thanks. Sorry to keep this open, but I now think it looks too big for the overall bar (it's taller than the menu to the left). Maybe remove the border around it? Also, the height of the button and the size of its text doesn't look quite right - is there any easy way of just making it fit the same height as the textbox?

**Comment by abeverley** [comment]
Actually, I've just been using Stripe, and they don't have a button at all. Is there any mileage in something like they do, or does that fall foul of accessibility?
image

**Comment by jkva** [comment]
> Actually, I've just been using Stripe, and they don't have a button at all.

It's more of an usability thing. Assuming Stripe's search has no autocomplete, they're assuming the user knows that "enter submits the query".

The input also lacks a label (using a placeholder instead) which is bad accessibility as well as a spec failure.

We have some issues to contend with when it comes to this PR, let's go over it in our morning call.

**Comment by abeverley** [comment]
Okay - this is what it looks for me: 
image

**Comment by jkva** [comment]
image

**Comment by jkva** [comment]
image

**Comment by jkva** [comment]
@abeverley I've repositioned and aligned things, care to have a look?

image

**Comment by abeverley** [comment]
Brilliant, thanks Job. Only minor point is that the bottom of the text is being chopped slightly, but I'd rather keep it like that and have the improved styling.

**Pull request merged**
